### ISSUE TITLE
CPController checklist

### ISSUE THREAD

**Issue by bpmn-os** [bpmn-os/bpmnos-engine#29]
- [ ] Constraints on `globalIndex` and `dataIndex`. 
- [ ] Entry of data owner has dataIndex := 0 and exit has dataIndex := number of modifiers
- [ ] If a modifier is not visited, it still increments the index and all globals or data attributes are deduced from previous
- [ ] Alternative status
- [ ] Merge status
- [ ] Sequential activity sequence
- [ ] Non-interrupting message event-subprocesses
- [ ] Lookup operator
- [ ] Multi-instance activities
- [ ] Generic expression operator should parse the symbol tree
- [ ] Add CP::GenericExpression for non-linear expressions 
- [ ] CP::GenericExpression or auxiliary variable is needed for `IndexedVariable`
       One solution could be to explicitly register potential key `index` variables:
```cpp
std::list<IndexVarible> CP::IndexedVariables::auxiliaryVariables;
struct IndexedVariable : Expression;
// ...
const Variable& CP::IndexedVariables::registerIndexVariable(const Variable& index) {
  auxiliaryVariables.emplace_back( type, name + "[" + index.name + "]", IndexedVariable(*this, index) );
  return auxiliaryVariables.back();
}
``` 
- [ ] ORTools interface
- [ ] Hexaly interface
