### ISSUE TITLE
Execution roadmap

### ISSUE THREAD

**Issue by rajgoel** [bpmn-os/bpmnos-engine#5]
Create tests and implement missing model support:

- [ ] Process
  - [x] Empty process  
  - [x] Simple process invokation
  - [x] Trivial process with start-task-end
  - [x] Event subprocess
    - [x] Interrupting event subprocess
      - [ ] Triggered by message 
      - [x] Triggered by timer
      - [x] Triggered by escalation
      - [x] Triggered by error 
    - [ ] Non-interrupting event subprocess
      - [ ] Triggered by message 
      - [ ] Triggered by timer
      - [x] Triggered by escalation
  - [x] Collaboration
- [x] Gateways
  - [x] Parallel gateway
    - [x] Split
      - [x] Token flow 
      - [ ] Status
    - [x] Join 
      - [x] Token flow 
      - [ ] Status
  - [x] Exclusive gateway
    - [x] Split
      - [x] Token flow 
      - [ ] Status
    - [x] Join 
      - [x] Token flow 
      - [ ] Status
  - [ ] Inclusive gateway
    - [ ] Split
      - [ ] Token flow 
      - [ ] Status
    - [ ] Join 
      - [ ] Token flow 
      - [ ] Status
  - [x] Event-based gateways
    - [x] Split
      - [x] Token flow 
      - [ ] Status
- [ ] Activities
    - [x] Task
    - [x] Subprocess
      - [x] Token flow 
      - [ ] Status
    - [ ] Resource activity
    - [ ] Request activity
    - [ ] Release activity
    - [ ] Job
- [ ] Events
  - [x] Throwing 
      - [x] Message #2
      - [x] Escalation
      - [x] Error 
  - [x] Catching
      - [x] Message #2
        - [x] Token flow 
        - [ ] Status
      - [x] Timer #3
        - [x] Token flow 
        - [ ] Status
      - [x] Escalation
        - [x] Token flow 
        - [ ] Status
      - [x] Error 
        - [x] Token flow 
        - [ ] Status
  - [x] Boundary events
    - [x] Interrupting boundary event
      - [x] Token flow 
      - [ ] Status
    - [x] Non-interrupting boundary event
      - [x] Token flow 
      - [ ] Status

Create tests and implement missing execution features:

- [ ] Status
  - [ ] Attributes
    - [ ] Constant attributes
    - [ ] Immutable attributes (constant after first definition) 
    - [ ] Shadowed attributes
  - [ ] Operators
    - [ ] Reference to non-existing attribute 
    - [ ] Reference to non-exisiting file or data-source
  - [ ] Restrictions 
    - [ ] Reference to non-existing attribute 
- [ ] Event-handler
  - [ ] DeterministicTaskCompletionHandler
    - [x] without status update
    - [ ] with status update
  - [ ] InstantEntryHandler
    - [x] without status update
    - [ ] with status update
  - [ ] InstantExitHandler
    - [x] without status update
    - [ ] with status update
  - [ ] Metronome
  - [ ] ReadyHandler
    - [x] without status update
    - [ ] with status update
  - [x] TimeWarp
- [ ] Controller
