### ISSUE TITLE
Static model analysis roadmap

### ISSUE THREAD

**Issue by rajgoel** [bpmn-os/bpmnos-engine#6]
- [ ] BPMN  #1
  - [ ] Unsupported events
    - [x] Link events 
    - [ ] Compensation events
    - [ ] Signal events
    - [ ] Conditional events
    - [ ] Cancel events
    - [ ] Multiple events
    - [ ] Parallel multiple events
  - [ ] Unsupported activities
    - [ ] Transactions
    - [ ] Ad-hoc activities
    - [ ] Compensation activities
    - [ ] Typed tasks
  - [ ] Other unsupported elements
    - [ ] Data pool
    - [ ] Data object
    - [ ] Complex gateways
  - [ ] Unsupported attributes
    - [ ] Multi-instance markers
    - [ ] Loop markers
    - [ ] Non-executable processes
    - [ ] Default flows
    - [ ] Conditional flows
    - [ ] Instantiating gateways
    - [ ] Empty pools in collaboration
    - [ ] Non-empty start events
  - [ ] Modelling issues
    - [x] https://github.com/bpmn-os/bpmnos/issues/4
    - [ ] Implicit start
    - [ ] Multiple start
    - [ ] (Sub)process with catching start  event
    - [ ] Event subprocess with untyped start event
    - [ ] Implicit split
    - [ ] Implicit join 
    - [ ] Deadlocks
    - [ ] Livelocks
    - [ ] Race conditions
    - [ ] Shadowed attribute names
    - [ ] Usage of undefined attributes in operators 
    - [ ] Usage of undefined attributes in restrictions 
    - [ ] Missing gatekeepers for exclusive and inclusive splits
    - [ ] Gatekeepers for sequence flows that should not have them 
- [ ] Data
  - [ ] Missing attribute data for ready event
